services:
  - type: web
    name: 18k-chat
    env: static
    buildCommand: npm install
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://xnujjoarvinvztccwrye.supabase.co
