services:
  - type: web
    name: 18k-chat
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VUE_APP_SUPABASE_URL
        value: https://xnujjoarvinvztccwrye.supabase.co
      - key: VUE_APP_SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self' https://xnujjoarvinvztccwrye.supabase.co wss://xnujjoarvinvztccwrye.supabase.co https://www.m9asia.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"
