services:
  - type: web
<<<<<<< HEAD
    name: 7dragon-chat-master
=======
    name: 7dragon-landing
>>>>>>> df80ad137dd19cd76afacca288d07998a0a24e54
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
    autoDeploy: true
